--Activar MasterKey
USE Master;
GO
CREATE MASTER KEY ENCRYPTION
BY PASSWORD='CxA2023.';
GO

-- Desactivar MasterKey
ALTER MASTER KEY
DROP ENCRYPTION BY SERVICE MASTER KEY;

--Eliminar MasterKey
Drop Master KEY;

--Ver usuarios y Certificados
SELECT USER_NAME() AS 'Nombre de Usuario';
SELECT * FROM sys.certificates;

-- CREAMOS UN CERTIFICADO DESDE EL MISMO MSSQL
CREATE CERTIFICATE DatabaseEncrypted
WITH 
SUBJECT='TRIGGERDB DATABASE ENCRYPTION';
GO

-- HACEMOS UN BACKUP DEL CERTIFICADO
BACKUP CERTIFICATE DatabaseEncrypted
TO FILE = 'C:\Certificados\Certificado_TDE'
WITH PRIVATE KEY (FILE='C:\Certificados\Certificado_TDE.pri',
ENCRYPTION BY PASSWORD='ServiciosWeb123.') 


-- CREAMOS EL DATABASE ENCRYPTION SOBRE LA BASE
USE ServiciosWeb 
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256 -- ALGORITMO
ENCRYPTION BY SERVER CERTIFICATE DatabaseEncrypted;

-- VERIFICAMOS EL ESTADO DE LAS BASES DE DATOS
SELECT NAME,IS_ENCRYPTED  
FROM SYS.DATABASES 
WHERE NAME = 'ServiciosWeb'

-- ENCENDEMOS EL TDE SOBRE LA BASE

ALTER DATABASE ServiciosWeb
SET ENCRYPTION ON;
GO

-- VERIFICAMOS EL ESTADO DE LAS BASES DE DATOS
SELECT NAME,IS_ENCRYPTED  
FROM SYS.DATABASES 
WHERE NAME = 'ServiciosWeb'


--- HACEMOS BACKUP DE NUESTRA BASE ENCRIPTADA
BACKUP DATABASE [AdventureWorks2019] 
TO  DISK = 
WITH NOFORMAT, INIT,  NAME = , 
SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO